### ISSUE TITLE
[FEAT] HealthKit workout detail data 받아오기

### ISSUE THREAD

**Issue by hryeong66** [Umpah-swim-wave/i-O-Swimmer#10]
## 💡 Issue

HealthKit에서 수영관련 데이터를 더 자세하게 받아오는 테스트 앱 만들기입니다.

## 📝  todo

- [x] HKSampleQuery predicate 자세한 사용법 찾기
- [ ] 수영 데이터를 session 단위로 받아오기

#### 🛠 수영데이터 정제하기
- [x] 우리나라 시간에 맞게 바꾸기
- [x] 단위랑 연결해서 출력하기
