### ISSUE TITLE
[FEAT] 루틴열람뷰 기본 기능 만들기

### ISSUE THREAD

**Issue by hryeong66** [Umpah-swim-wave/i-O-Swimmer#16]
## 💡 Issue

루틴열람뷰
|루틴열람뷰|루틴편집뷰|
|--|--|
|<img width="177" alt="image" src="https://user-images.githubusercontent.com/59547116/128291297-3ce61f38-4dcf-4c7b-b636-ad0aa6dcc1cd.png">|<img width="177" alt="image" src="https://user-images.githubusercontent.com/59547116/128291408-3e5f2900-ec91-475a-8173-d0d3a4abd253.png">|

우선 버튼과 네이게이션은 논의 후 추가하겠습니다

## 📝  todo
- [ ] table header로 루틴 설명 부분 뷰 넣기
- [ ] tableview 기본 section과 row들 구현
- [ ] 루틴편집뷰 삭제와 드레그앤 드롭 구현
- [ ] 동적으로 row 추가하기
