### ISSUE TITLE
[FEAT] Firebase Analytics 연결

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#22]
## 💡 Issue
Google Analytics 연결을 위한 Firebase 파기 및 라이브러리 가져오기

## 📝  todo
- [ ] Google Analytics 연결을 위해서 Firebase 파기
- [ ] Pod에 불러와서 연결 구현
- [ ] Umbrella 사용 고려해보기
