### ISSUE TITLE
[CHORE] 홈 뷰 변경된 부분 반영

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#28]
## 💡 Issue
홈 뷰 변경된 사항, 반영하기

## 📝  todo
- [x] 상단 헤더 부분 생성
- [x] 네비게이터 바 생성
- [x] 필터 콜렉션 뷰 생성
- [x] Detail 테이블 뷰 생성(contentView로)
- [x] 하단 모달 카드 뷰 생성
