### ISSUE TITLE
[FEAT] Half View 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#37]
## 💡 Issue
반뷰를 State에 따라서 변화하도록 구현

## 📝  todo
- [x] State에 따라서 코드 구성
- [x] 바로바로 Title이 변경 되도록 구성
- [x] 내부에 날짜 데이터 반영
- [x] 영법 수정하기 기능 구현
- [x] 영법 합치기 기능 구현
- [x] 영법 선택 구현
