### ISSUE TITLE
[FEAT] Home Cell 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#4]
## 💡 Issue
Home Collection View Cell Custom해두기

## 📝  todo
- [x] Cell and VC 연결
- [x] Cell Shadow 추가
- [x] Route Register Cell 레이아웃(등록뷰)
- [x] Route Select Cell 레이아웃
- [x] header 추가
