### ISSUE TITLE
[CHORE] 기록탭 코드 정리

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#42]
## 💡 Issue

기록탭에 무분별하게 쌓여있는 코드들을 정리합니다.
State를 적극활용해서 더 좋은 코드를 만들 예정입니다.

## 📝  todo
- [ ] enum 정리
- [ ] state별로 정리 생각(class를 생성해야하나)
- [ ] ViewModel, or Manager 파일을 생성해서 관리
- [ ] BaseViewController 추가
- [ ] 반뷰를 ContentView로 빼기(?)
- [ ] Clean Code 공부
- [ ] Clean 아키텍쳐 공부
- [ ] Testable한 코드로 만들기
