### ISSUE TITLE
[FEAT] 홈루틴, 반뷰 tableview 구성하기

### ISSUE THREAD

**Issue by hryeong66** [Umpah-swim-wave/i-O-Swimmer#47]
## 💡 Issue

홈루틴, 반뷰 tableview cell 만들어서 구성할겁니다!

## 📝  todo
- [ ] tableview cell ui 만들기
- [ ] tableview cell 에 넣을 데이터 모델 만들기
- [ ] tableview cell 연결하기
- [ ] 홈 루틴, 반뷰에 연결하기
- [ ] tableview is selected 되었을 때 model 반환되도록 rx 이용해서 짜기
