### ISSUE TITLE
[REFACTOR] 코드 2차 리팩토링

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#53]
## 💡 Issue
ViewModel 제대로 적용해보기

## 📝  todo
- [ ] ViewModel에 Helper코드 넣기
- [ ] 뷰안에 코드를 더 쪼개보기
- [ ] 중복 코드 삭제 및 간결하게 변경
