### ISSUE TITLE
[CHORE] 디자인 수정사항 반영

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#54]
## 💡 Issue
디자인 수정 사항을 반영합니다.

## 📝  todo
- [x] 폰트 굵기 수정
- [x] 버튼 컬러, height 수정
- [x] 완료, 취소버튼 위치 변경
- [x] 딱지 컬러 변경
- [x] Popup창에 폰트 설정
- [x] 영법 선택 하이라이트 컬러 변경
