### ISSUE TITLE
[FEAT] 서버 기본 셋팅과 기록 보내기 api 연결하기

### ISSUE THREAD

**Issue by hryeong66** [Umpah-swim-wave/i-O-Swimmer#55]
## 💡 Issue

 서버 기본 셋팅과 기록 보내기 api 연결하기입니다. 
## 📝  todo
- [x] 모야를 이용한 서버 기본 셋팅
- [x] 기록 보내기 api 연결하기

### 🐳HealthKit 추가로 해야할 일 
- [x] 심박수 데이터 가져오기
- [x] 심박수 데이터 평균 내서 model에 담기
- [x] source data 가져온 후 다른 작업되도록 HealthKit 수정하기
