### ISSUE TITLE
[FEAT] DetailedRoutineView 기본 Layout 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#6]
## 💡 Issue
DetailedRoutineView의 기본 레이아웃을 미리 구현해둘겁니다.

## 📝  todo
- [x] View push 연결시키기
- [x] background 투명하게 하기
- [x] Base View 올리기
