### ISSUE TITLE
[CHORE] 루틴 탭 Design QA 반영

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#67]
## 💡 Issue

루틴 탭 Design QA를 반영합니다.

## 📝  todo
- [x] **텍스트 상세 체크**
- [x] **루틴 카드 delete 버튼 추가 (ic_trash)**
- [x] 루틴 카드 내부에 타이틀 ↔ 딱지들 간격 체크
