### ISSUE TITLE
[CHORE] 루틴 상세뷰 디자인 QA 반영

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#69]
## 💡 Issue

루틴 상세뷰 디자인 QA를 반영합니다.

## 📝  todo
- [x] **텍스트 상세 체크 (설명, 세트 명)**
- [x] **거리(m):오른쪽으로 간격 조금만 더 붙이기** 
- [x] 자유영 → 자유형, 배영, 평영, 접영 ~ 기본 영법 수정
- [x] 전체 폰트 두께 체크 : 영법/거리/시간 → regular  ||   상세 내용들 → text
