### ISSUE TITLE
[REFACTOR] MainVC 리팩토링 진행

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#73]
## 💡 Issue

반 뷰, 기록 뷰, 루틴 뷰를 모두 가지고 있는 MainVC 자체가 너무 비대해서 리팩토링을 진행합니다. 
반 뷰에서 버그가 많이 생겨서 리팩토링을 해야할 듯 합니다...🥲

## 📝  todo
- [x] TableView 담당 VC 생성
- [x] CardView 담당 VC 생성
- [x] RxSwift 에 맞게끔 코드 수정
- [x] 접근 제한자 정리
- [x] Mark 정리
- [x] 복잡한 로직 수정
