### ISSUE TITLE
[REFACTOR] Popup 관련 부분 리팩토링

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#79]
## 💡 Issue

Popup 뷰(SelectedRangeVC, SelectedStrokeVC)와 관련된 Component, Cell들을 정리합니다.

## 📝  todo
- [x] VC 리팩토링
- [x] Component 정리
- [x] StrokesTVC 정리
- [x] Strokes 네이밍 변경
- [x] 접근 제한자, 주석 정리
- [x] 복잡한 로직 정리
