### ISSUE TITLE
[DOCS] HealthKit 기본 사용법 정리

### ISSUE THREAD

**Issue by hryeong66** [Umpah-swim-wave/i-O-Swimmer#8]
## 💡 Issue

HealthKit 기본 사용법 정리할 문서 작성

## 📝  todo

- [ ] HealthKit 기본 셋팅
- [ ] read, write 데이터 권한 요청하기
- [ ] 운동데이터 이외 HKSample query하는 방법
- [ ] 운동 데이터 query하기
- [ ] 운동데이터 query에서 predicateFor 관련메소드 사용 정리
