### ISSUE TITLE
[BUG] 기록 주간, 월간 반뷰 높이 문제 

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#85]
## 🐞 버그 설명

기록 주간, 월간 반뷰에서 높이가 애매하게 나타납니다. 그 외 다수의 문제를 해결 예정

## 📝 todo
- [x] 기록 주간, 월간 반뷰 높이 수정
- [x] 탭 누르면 반뷰가 이상하게 상태 변경하는 문제 해결
- [x] 리로드시 뷰가 내려가는 문제 해결
