### ISSUE TITLE
[FIX] 루틴상세뷰 디자인 QA

### ISSUE THREAD

**Issue by hryeong66** [Umpah-swim-wave/i-O-Swimmer#86]
## 💡 Issue

루틴상세뷰 디자인 QA합니다. 
## 📝  todo
- [x] 영법 선택을 안했을 경우에 이전에 선택했던 영법으로 넘겨주기
- [ ] 영법과 m를 선택하면 시간 시정되도록 임시로 계산해놓기 → (PM님 만나서 얘기해보기)
- [x] font 디자인 QA
- [x] 정렬맞추기
- [ ] 삭제 버튼 안눌리는 부분 확인하기
