### ISSUE TITLE
[FEAT] 기록 조회 API 연결

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#89]
## 💡 Issue

기록 조회 API를 연결합니다. 

## 📝  todo
- [x] 일간 기록 조회
- [x] 주간 기록 조회
- [x] 월간 기록 조회
- [x] 유저 날짜 조회
