### ISSUE TITLE
[CHORE] HomeView UI 수정

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#9]
## 💡 Issue
바뀐 HomeView UI 레이아웃으로 코드를 수정합니다.

## 📝  todo
_디자이너한테 물어보고 나서 todo 추가_
- [ ] 루틴 선택하기 Cell Layout 변경
- [ ] Route 부분 레이아웃 전면 수정
- [ ] alert 배너 생성
