### ISSUE TITLE
[FEAT] 일간 반 뷰에 데이터 구현하기

### ISSUE THREAD

**Issue by YoonAh-dev** [Umpah-swim-wave/i-O-Swimmer#93]
## 💡 Issue

일간 반 뷰에 데이터를 넣습니다. 
데이터 Merge(수정)를 구현해봅니다.

## 📝  todo
- [ ] 일간 반 뷰 데이터 넣기
- [ ] 데이터 Merge 기능 구현
- [ ] Merge하고나서 저장하기 구현
